# Generated by Django 4.2.26 on 2025-12-05 03:18

from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="상품명")),
                (
                    "thumbnail",
                    models.URLField(max_length=500, verbose_name="썸네일 URL"),
                ),
                ("price", models.IntegerField(verbose_name="가격")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    common.fields.ForceAutoNowDateTimeField(
                        auto_now=True, verbose_name="수정일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
    ]
