# Generated by Django 4.2.26 on 2025-12-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wish_item_box", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.BigIntegerField(verbose_name="상품 ID")),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="상품명"),
                ),
                ("product_price", models.IntegerField(verbose_name="상품 가격")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "wish_item_box",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_items",
                        to="wish_item_box.wishitembox",
                        verbose_name="찜 서랍",
                    ),
                ),
            ],
            options={
                "verbose_name": "찜 상품",
                "verbose_name_plural": "찜 상품",
                "db_table": "wish_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
