# Generated by Django 4.2.26 on 2025-12-04 13:06

from django.db import migrations

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wish_item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="updated_at",
            field=common.fields.ForceAutoNowDateTimeField(
                auto_now=True, verbose_name="수정일시"
            ),
        ),
    ]
