# Generated by Django 4.2.26 on 2025-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("username", models.CharField(max_length=150, verbose_name="사용자명")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
            ],
            options={
                "verbose_name": "회원",
                "verbose_name_plural": "회원",
                "db_table": "members",
            },
        ),
    ]
