# Generated by Django 4.2.26 on 2025-12-04 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WishItemBox",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="찜 서랍 이름")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_item_boxes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "찜 서랍",
                "verbose_name_plural": "찜 서랍",
                "db_table": "wish_item_boxes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="wishitembox",
            constraint=models.UniqueConstraint(
                fields=("member", "name"), name="unique_member_wish_item_box_name"
            ),
        ),
    ]
