# Generated by Django 4.2.26 on 2025-12-05 04:35

from django.db import migrations

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wish_item_box", "0002_wishitembox_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishitembox",
            name="updated_at",
            field=common.fields.ForceAutoNowDateTimeField(auto_now=True),
        ),
    ]
